Typo fix and
codeforbtv/expunge-vt pull request #159
Opened 2021-06-20 23:12 UTC by jakedurell

Made this branch with goal of making transferable case file. First did a type fix and remove VCOL content. Thought we could go ahead and deploy that now.

2021-07-19 12:26 UTC, doub1ejack requested changes
Before we remove the code, it would be nice to put together some good Odyssey sample dockets and make sure the [Demo section of the README](https://codeforbtv.org/expunge-vt/#:~:text=although%20you%20can%E2%80%99t%20generate%20real%20petitions%20without%20data%20access%2C%20you%20can%20give%20it%20a%20test%20run%20on%20these%20three%20sample%20dockets.) still works smoothly. (I often point people to that page when they're trying to understand exactly how the extension works.)

2021-07-19 12:26 UTC, doub1ejack commented on extensionDirectory/popup.js
> +      // DEMO & DEV: TODO - currently we only have demo samples for VCOL dockets
It looks like the VTCO sample files haven't been changed or removed. We should probably do that as part of this PR too.

2021-07-19 12:29 UTC, doub1ejack commented
Note, I cherry-picked the two text related commits (`typo interests of justice fix` and `amend sealing petition`) to another branch, merged that into master so they could be deployed separately, and merged master back into this branch. 

Now this branch only has the VT Courts Online removal changes. I'll publish the typo/text fixes from master to production now...

2021-07-29 12:45 UTC, merged

2021-07-29 12:48 UTC, jakedurell commented
@doub1ejack - nice work this morning. Do we want to put that warning in? Are you still getting that deploy error?